"""
Preference Memory Module for Modified CoCoMo.

Manages the model's self-generated preference description:
  - Extraction: prompts the model to articulate its own preferences
  - Refinement: iteratively improves the self-description after each training epoch
  - Injection: prepends the preference memory to prompts at inference time

The memory is a natural language string generated BY the model, ABOUT the model.
It evolves across distillation rounds as the model's behavior changes.
"""
from __future__ import annotations

import os
import json
import torch
from datetime import datetime

from config import (
    MEMORY_EXTRACTION_PROMPT,
    MEMORY_REFINEMENT_PROMPT,
    MEMORY_INJECTION_TEMPLATE,
    MEMORY_MAX_TOKENS,
)


class PreferenceMemory:
    """
    Stores and manages the model's self-generated preference description.

    The memory evolves across distillation rounds:
      Round 0: Initial extraction (model describes preferences from scratch)
      Round N: Refinement (model reads previous memory + updates based on new experience)
    """

    def __init__(self, save_dir: str = "modified_cocomo/memory"):
        self.save_dir = save_dir
        os.makedirs(save_dir, exist_ok=True)
        self.current_memory: str = ""
        self.history: list[dict] = []
        self._load_latest()

    def _load_latest(self):
        history_path = os.path.join(self.save_dir, "memory_history.json")
        if os.path.exists(history_path):
            with open(history_path) as f:
                self.history = json.load(f)
            if self.history:
                self.current_memory = self.history[-1]["memory"]

    def _save(self):
        history_path = os.path.join(self.save_dir, "memory_history.json")
        with open(history_path, "w") as f:
            json.dump(self.history, f, indent=2)
        current_path = os.path.join(self.save_dir, "current_memory.txt")
        with open(current_path, "w") as f:
            f.write(self.current_memory)

    def extract(self, model, tokenizer) -> str:
        """
        Initial extraction: ask the model to describe its preferences from scratch.
        Used at round 0 (before any refinement).
        """
        response = self._generate(model, tokenizer, MEMORY_EXTRACTION_PROMPT)
        self.current_memory = response
        self.history.append({
            "round": len(self.history),
            "type": "extraction",
            "memory": response,
            "timestamp": datetime.now().isoformat(),
        })
        self._save()
        return response

    def refine(self, model, tokenizer) -> str:
        """
        Refinement: show the model its previous self-description and ask it to update.
        Used after each training epoch.
        """
        if not self.current_memory:
            return self.extract(model, tokenizer)

        prompt = MEMORY_REFINEMENT_PROMPT.format(previous_memory=self.current_memory)
        response = self._generate(model, tokenizer, prompt)
        self.current_memory = response
        self.history.append({
            "round": len(self.history),
            "type": "refinement",
            "memory": response,
            "timestamp": datetime.now().isoformat(),
        })
        self._save()
        return response

    def inject(self, prompt: str) -> str:
        """
        Prepend the current preference memory to a prompt.
        Returns the augmented prompt ready for generation.
        """
        if not self.current_memory:
            return prompt
        prefix = MEMORY_INJECTION_TEMPLATE.format(preference_memory=self.current_memory)
        return prefix + prompt

    def get_memory(self) -> str:
        return self.current_memory

    def get_history(self) -> list[dict]:
        return self.history

    def _generate(self, model, tokenizer, prompt: str) -> str:
        messages = [{"role": "user", "content": prompt}]
        encoded = tokenizer.apply_chat_template(
            messages, return_tensors="pt", return_dict=True
        ).to(model.device)
        prompt_len = encoded["input_ids"].shape[1]
        with torch.no_grad():
            outputs = model.generate(
                **encoded,
                max_new_tokens=MEMORY_MAX_TOKENS,
                temperature=0.7,
                do_sample=True,
                pad_token_id=tokenizer.eos_token_id,
            )
        generated = tokenizer.decode(outputs[0][prompt_len:], skip_special_tokens=True)
        del encoded, outputs
        torch.cuda.empty_cache()
        return generated
